export const queryKeys = {
  me: ['auth', 'me'] as const,
  dashboard: (storeId: string) => ['dashboard', storeId] as const,
  dashboardExtended: (storeId: string) => ['dashboard', 'extended', storeId] as const,
  syncHealth: ['sync', 'health'] as const,
  products: (filters: Record<string, unknown>) => ['products', filters] as const,
  product: (id: string) => ['product', id] as const,
  categories: (storeId: string) => ['categories', storeId] as const,
  locations: (storeId: string) => ['locations', storeId] as const,
  sessions: (filters: Record<string, unknown>) => ['sessions', filters] as const,
  session: (id: string) => ['session', id] as const,
  sessionLines: (id: string, filter?: string) => ['session', id, 'lines', filter] as const,
  audit: (filters: Record<string, unknown>) => ['audit', filters] as const,
  users: (storeId: string) => ['users', storeId] as const,
  storeProfile: (storeId: string) => ['store', storeId] as const,
  storeSettings: (storeId: string) => ['store', storeId, 'settings'] as const,
};
